---
version: '3.5'
services:
  cba_tests:
    image: cbauitests
    build:
      context: .
      shm_size: '5gb'
      dockerfile: Dockerfile
    shm_size: '5gb'
    working_dir: /usr/src/project
    environment:
      - PYTHONPATH
      - BROWSER
      - DEVICENAME
      - RESPONSIVE
    volumes:
      - .:/usr/src/project
